/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * Control de altura de un "drone conceptual" por REALIMENTACIÓN NEGATIVA.
 *
 * Node-RED envía un setpoint "HEIGHT:<3-20>" que el STM32 acepta por
 * CUALQUIERA de sus dos enlaces, los dos escuchando en simultáneo:
 *
 *   CABLE      USART2 (PA2/PA3) -> Virtual COM Port del ST-Link, por USB
 *   BLUETOOTH  UART4  (PA0/PA1) -> módulo HC-05 / HC-10
 *
 * El HC-SR04 (TIM1 Input Capture) mide la altura actual y realimenta el
 * lazo: height_control calcula el error y aplica acción PID sobre una base
 * de empuje, comandando el PWM de los motores (TIM2_CH1 -> ENA/ENB).
 * La telemetría sale por los dos puertos a la vez.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "distance.h"
#include "motor.h"
#include "height_control.h"
#include "comandos.h"

#define HCSR04_TRIG_PORT             GPIOA
#define HCSR04_TRIG_PIN              GPIO_PIN_9   /* D8 / PA9 */

/* El período del lazo lo define height_control.h (CONTROL_PERIODO_MS),
 * porque el término derivativo depende de él para escalar la velocidad. */
#define PERIODO_REPORTE_MS           500U

void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_UART4_Init(void);
static void MX_TIM1_Init(void);
static void Reportar_Estado(void);

TIM_HandleTypeDef htim1;

UART_HandleTypeDef huart2;   /* PA2/PA3 - depuración por ST-Link */
UART_HandleTypeDef huart4;   /* PA0/PA1 - módulo HC-10 */

int main(void)
{
	HAL_Init();
	SystemClock_Config();
	MX_GPIO_Init();
	MX_USART2_UART_Init();
	MX_UART4_Init();
	MX_TIM1_Init();

	/* Sensor de distancia (HC-SR04 / TIM1 Input Capture). */
	HAL_TIM_IC_Start_IT(&htim1, TIM_CHANNEL_1);
	HAL_GPIO_WritePin(HCSR04_TRIG_PORT, HCSR04_TRIG_PIN, GPIO_PIN_RESET);

	Motor_Inicializar();
	ControlAltura_Inicializar();
	Comandos_Inicializar();

	while (1)
	{
	    uint32_t Ahora = HAL_GetTick();

	    Comandos_Procesar(); /* consignas HEIGHT: por cable o por Bluetooth */

	    /* ── Lazo de control (10 Hz) ── */
	    static uint32_t ultimo_control = 0U;
	    if ((Ahora - ultimo_control) >= CONTROL_PERIODO_MS)
	    {
	        ultimo_control = Ahora;

	        Distancia_Actualizar();                           /* realimentación */
	        ControlAltura_Actualizar(Distancia_ObtenerCm());  /* acción PD */
	    }

	    /* ── Reporte (2 Hz), fuera del lazo para no frenarlo ── */
	    static uint32_t ultimo_reporte = 0U;
	    if ((Ahora - ultimo_reporte) >= PERIODO_REPORTE_MS)
	    {
	        ultimo_reporte = Ahora;
	        Reportar_Estado();
	    }
	}
}

/* Arma la línea de telemetría y la manda por los dos enlaces a la vez, así
 * se ve igual desde el cable o desde el Bluetooth.
 *
 * Es una sola línea, compacta pero legible: la parsea Node-RED y también se
 * entiende leyéndola en una terminal. Antes había además una línea aparte en
 * prosa, pero con dos puertos duplicaba el tráfico sin aportar nada.
 *
 * Los valores se imprimen con aritmética entera a propósito: usar %f en
 * snprintf exigiría enlazar con -u_printf_float y ocupar más flash. */
static void Reportar_Estado(void)
{
    char buffer[96];
    int  altura_x10;
    int  objetivo_x10;
    int  vel_x10;
    int  len;

    altura_x10   = (int)(Distancia_ObtenerCm() * 10.0f);
    objetivo_x10 = (int)(ControlAltura_ObtenerObjetivoCm() * 10.0f);
    vel_x10      = (int)(ControlAltura_ObtenerVelocidadVerticalCmS() * 10.0f);

    /* H  altura medida    SP setpoint      V  empuje aplicado
     * VZ velocidad vert.  S  sensor OK     L  enlace del último comando */
    len = snprintf(buffer, sizeof(buffer),
                   "H:%d.%d,SP:%d.%d,V:%u,VZ:%d.%d,S:%u,L:%s\n",
                   altura_x10 / 10, abs(altura_x10 % 10),
                   objetivo_x10 / 10, abs(objetivo_x10 % 10),
                   (unsigned int)ControlAltura_ObtenerEmpujePct(),
                   vel_x10 / 10, abs(vel_x10 % 10),
                   (Distancia_UltimaFueValida() != 0U) ? 1U : 0U,
                   Comandos_ObtenerUltimoOrigenTexto());

    if (len > 0)
    {
        Comandos_EnviarTelemetria(buffer);
    }
}











void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE3);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = 16;
  RCC_OscInitStruct.PLL.PLLN = 336;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV4;
  RCC_OscInitStruct.PLL.PLLQ = 2;
  RCC_OscInitStruct.PLL.PLLR = 2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief USART2 Initialization Function
  * @note  Terminal de depuración por ST-Link (PA2/PA3). Vuelve a 115200
  *        porque ya no comparte el puerto con el HC-10.
  */
static void MX_USART2_UART_Init(void)
{

  /* USER CODE BEGIN USART2_Init 0 */

  /* USER CODE END USART2_Init 0 */

  /* USER CODE BEGIN USART2_Init 1 */

  /* USER CODE END USART2_Init 1 */
  huart2.Instance = USART2;
  huart2.Init.BaudRate = 115200;
  huart2.Init.WordLength = UART_WORDLENGTH_8B;
  huart2.Init.StopBits = UART_STOPBITS_1;
  huart2.Init.Parity = UART_PARITY_NONE;
  huart2.Init.Mode = UART_MODE_TX_RX;
  huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart2.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart2) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN USART2_Init 2 */

  /* USER CODE END USART2_Init 2 */

}

/**
  * @brief UART4 Initialization Function
  * @note  Puerto exclusivo del HC-10 (PA0 = TX, PA1 = RX), a 9600 baudios
  *        para coincidir con el módulo BLE.
  */
static void MX_UART4_Init(void)
{
  huart4.Instance = UART4;
  huart4.Init.BaudRate = 38400;
  huart4.Init.WordLength = UART_WORDLENGTH_8B;
  huart4.Init.StopBits = UART_STOPBITS_1;
  huart4.Init.Parity = UART_PARITY_NONE;
  huart4.Init.Mode = UART_MODE_TX_RX;
  huart4.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart4.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart4) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief TIM1 Initialization Function
  * @note  Input Capture CH1 en PA8 (D7) para ECHO del HC-SR04.
  *        1 cuenta = 1 us con TIM1CLK = 84 MHz, PSC = 83.
  */
static void MX_TIM1_Init(void)
{
  TIM_IC_InitTypeDef sConfigIC = {0};

  htim1.Instance = TIM1;
  htim1.Init.Prescaler = 83;
  htim1.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim1.Init.Period = 65535;
  htim1.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim1.Init.RepetitionCounter = 0;
  htim1.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  if (HAL_TIM_IC_Init(&htim1) != HAL_OK)
  {
    Error_Handler();
  }

  sConfigIC.ICPolarity = TIM_INPUTCHANNELPOLARITY_RISING;
  sConfigIC.ICSelection = TIM_ICSELECTION_DIRECTTI;
  sConfigIC.ICPrescaler = TIM_ICPSC_DIV1;
  sConfigIC.ICFilter = 0;
  if (HAL_TIM_IC_ConfigChannel(&htim1, &sConfigIC, TIM_CHANNEL_1) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
/* USER CODE BEGIN MX_GPIO_Init_1 */
/* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOH_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();

  /*Configure GPIO pin : B1_Pin */
  GPIO_InitStruct.Pin = B1_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_IT_FALLING;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  HAL_GPIO_Init(B1_GPIO_Port, &GPIO_InitStruct);

  /* PA5 (LD2) NO se configura como salida digital: es la salida PWM
   * TIM2_CH1 hacia ENA del L298N, y la configura Motor_Inicializar(). */

/* USER CODE BEGIN MX_GPIO_Init_2 */
  GPIO_InitStruct.Pin = GPIO_PIN_9;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_RESET);
/* USER CODE END MX_GPIO_Init_2 */
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
